name: jewelry_app
description: A beautiful jewelry mobile app with admin and user roles.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.1.0
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  screenshot: ^2.1.0
  sqflite: ^2.3.0
  crypto: ^3.0.3
  http: ^1.1.0
  path: ^1.8.3
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/